language: python
sudo: false

# Support 2.7 as last 2.x release and 3.4+
python:
    - 2.7
    - 3.6
    - 3.7

install:
    # install for test coverage analyzes
    - pip install coveralls
    - pip install html5lib
    - pip install soupsieve==1.8
    # install for doc build / publish
    - pip install sphinx
    - pip install sphinxcontrib-images
    # Is normally installed due to dependency in "setup.py" but travis
    # build installs this as egg which breaks the current import test so try
    # to install it manually before.
    - pip install simpleTR64
    # install for for import tests
    - if [ $TRAVIS_PYTHON_VERSION = '2.7' ]; then pip install snakefood; fi
    #- find /opt/python/2.7.*/lib/python2.7
    #- find /home/travis/virtualenv/python2.7.*/lib/python2.7

addons:
  apt:
    packages:
        - realpath
        - python-six

# Run tests with coverage checking
script:
    - cd $TRAVIS_BUILD_DIR
    - coverage run --source=pmatic setup.py test

after_success:
    # Upload coverage
    - coveralls

after_script:
    # eventually run snapshot build. Make the whole build fail when it fails
    - if [ $TRAVIS_TEST_RESULT == 0 ] && [ $TRAVIS_PYTHON_VERSION = '2.7' ] && [ $TRAVIS_BRANCH = 'master' ] && [ $TRAVIS_PULL_REQUEST = 'false' ]; then make travis-build travis-doc; fi

# Secret for uploading snapshot builds
env:
  global:
    secure: UVubH1quHSxuh3bOYJqdcjQuZCEngdQECd5/B8ImzkY2QY0YwaN5wivbTEb9mKeYMSUYX6C2+K7plz5g3fYoOIwX0Y9DQtLb7xwERGiA5e0vADRZ3JjglEa5FHyY3gdOdl2eToyQG/afdI6CFGWWLVfj47mJi2V7aHPlA9mfdDElyX/h+xQv2Emkzcnk5W5YH720t7hoDLZ4w/EVd/gJTNK8TwVHOYiGkeDEBjcG/h4uriVmWWll82TvzJ0RRD/jm9B2jKJBtRIn+fitUgiuFo0PHRfuNBNiwS7WzkqZZPJ7DwgLoMGy6ZcqGl7Kb50eBAiP6XHyPSsqO2zFZon7vx4YIyXQuzxjjYRPhkb9eprxoOHWXlysNFMEbtmV+SBbKBK2V9fpHZtyI1643O/s7EtVvH4Ad9c+/I0gESM8GbSwgFPKCpIJdjMcz1SJb4s7HkLFo2H1NQTm3fchQxLy6EW7JTT6XE0+vFoiXoEiGCP/KDfVL/AaCdvp1IwJ4DKGW4eGREjhIj6vJVF0vw9HVZv32nKINajgeOW+M3AzxIZS5oFQzj6mc2eXTjVWYeDPckYY+pVdFOnUml9n7ZytKzl3WwzzHqmSdiYLCNBDafPcfEn6P6eiCBNFAMMTFQM5Laal7DKLo6eVUTWR9UXkmJhbEu3QGiHK/JfvuIQKc2k=
