#!/bin/sh

# source standard vars
. ./python-wrapper

BIN_DIR=/usr/local/bin
CONFIG_DIR=/usr/local/etc/config
PROFILE_DIR=/usr/local/etc/profile.d
WWW_DIR=${CONFIG_DIR}/addons/www/${ADDON_NAME}
RCD_DIR=${CONFIG_DIR}/rc.d

# log file infos
LOG_FILE=$ADDON_DIR/etc/${ADDON_NAME}-install.log
exec 1<&-
exec 2<&-
exec 1<>$LOG_FILE
exec 2>&1

echo "starting installation of addon ${ADDON_NAME} w/ ${PYTHON_VER} at $(date)"
echo $@ 

echo -e "\n mount /usr/local if not already mounted"
if [ "$1" = "" ]; then
  echo "CCU1"
  lcdtool "installing pmatic   "
  mount -t yaffs /dev/mtdblock3 /usr/local
elif [ "$1" = "CCU2" ]; then
  echo "CCU2"
  if ! mount | grep ^ubi1:user.*rw >/dev/null 2>&1; then
      mount -t ubifs ubi1:user /usr/local
  fi
elif [ "$1" == "HM-RASPBERRYMATIC" -o "$1" == "CCU3" ]; then
  echo "Installing on CCU3/RaspberryMatic ($1)" 
fi

# remove files of old versions (same as in pmatic.init)
echo -e "\n remove files of old versions"
rm $BIN_DIR/pmatic-manager
rm $PROFILE_DIR/python-addons.sh
# FIXME: consider a clean deinstall w/o deleting customized changes 
#  rm -rf $ADDON_DIR
rm -rf $ADDON_DIR/python
rm -rf $ADDON_DIR/pmatic
rm -rf $ADDON_DIR/examples
rm -rf $ADDON_DIR/manager_static
rm -rf $WWW_DIR

echo -e "\n create directories"
if [ ! -d $BIN_DIR ]; then
    mkdir -p $BIN_DIR
    chmod 755 $BIN_DIR
fi

if [ ! -d $ADDON_DIR ]; then
    mkdir -p $ADDON_DIR
    chmod 755 $ADDON_DIR
fi

if [ ! -d $RCD_DIR ]; then
    mkdir -p $RCD_DIR
    chmod 755 $RCD_DIR
fi

if [ ! -d $ADDON_DIR/scripts ]; then
    mkdir -p $ADDON_DIR/scripts
    chmod 755 $ADDON_DIR/scripts
fi

if [ ! -d $ADDON_DIR/etc ]; then
    mkdir -p $ADDON_DIR/etc
    chmod 755 $ADDON_DIR/etc
fi

if [ ! -d $WWW_DIR/etc ]; then
    mkdir -p $WWW_DIR
    chmod 755 $WWW_DIR
fi

cp pmatic-manager $BIN_DIR/
chmod +x $BIN_DIR/pmatic-manager

# copy all stuff and setup rc.d
echo -e "copy all stuff and setup rc.d"
cp -R python manager_static $ADDON_DIR/
cp -R examples $ADDON_DIR/scripts/
cp -R pmatic $ADDON_DIR/python/lib/$PYTHON_VER
ln -s python/lib/$PYTHON_VER/pmatic $ADDON_DIR/pmatic
cp pmatic.init $RCD_DIR/pmatic
chmod +x $RCD_DIR/pmatic
cp python-wrapper $PROFILE_DIR/python-addons.sh
chmod +x $PROFILE_DIR/python-addons.sh
# cp /tmp/${ADDON_NAME}-install3.log $ADDON_DIR/

# copy www stuff
echo -e "\n copy www stuff"
cp -af www/* ${WWW_DIR}/
chmod -R 755 $WWW_DIR
sync

echo -e "\n finish"
if [ "$1" = "" ]; then
  echo "CCU1"
  lcdtool "Reboot...             "
  lcdtool -a 0x40 -t bin 00
  echo "x" > /dev/watchdog
  reboot
  while true ; do true ;  done
elif [ "$1" = "CCU2" ]; then
  echo "CCU2"
  # CCU2 always reboots after Addon/Firmware Update
elif [ "$1" = "CCU3" ]; then
  echo "CCU3"
  # CCU3 always reboots after Addon/Firmware Update
elif [ "$1" = "HM-RASPBERRYMATIC" ]; then
  echo "finish HM-RASPBERRYMATIC"
  # RASPBERRYMATIC always reboots after Addon/Firmware Update
fi
