#!/bin/sh

ADDON_NAME=pmatic
BIN_DIR=/usr/local/bin
CONFIG_DIR=/usr/local/etc/config
ADDON_DIR=${CONFIG_DIR}/addons/${ADDON_NAME}
WWW_DIR=${CONFIG_DIR}/addons/www/${ADDON_NAME}
RCD_DIR=${CONFIG_DIR}/rc.d
#PYTHON_VER=python3.8
PYTHON_VER=python2.7

LOG_FILE=/tmp/${ADDON_NAME}-install3.log

exec 1<&-
exec 2<&-
exec 1<>$LOG_FILE
exec 2>&1

echo "starting installation of addon ${ADDON_NAME} w/ PY3 at $(date)" >>$LOG_FILE
echo $@ >>$LOG_FILE

echo "mount /usr/local if not already mounted" >>$LOG_FILE
if [ "$1" = "" ]; then
  echo "CCU1"
  lcdtool "installing pmatic   "
  mount -t yaffs /dev/mtdblock3 /usr/local
elif [ "$1" = "CCU2" ]; then
  echo "CCU2"
  if ! mount | grep ^ubi1:user.*rw >/dev/null 2>&1; then
      mount -t ubifs ubi1:user /usr/local
  fi
elif [ "$1" == "HM-RASPBERRYMATIC" -o "$1" == "CCU3" ]; then
  echo "Installing on CCU3/RaspberryMatic" 
  mount /usr/local
fi

# remove files of old versions (same as in pmatic.init)
echo "remove files of old versions" >>$LOG_FILE
rm $BIN_DIR/$PYTHON_VER $BIN_DIR/python3 
rm $BIN_DIR/$PYTHON_VER $BIN_DIR/$PYTHON_VER 
rm $BIN_DIR/pmatic-manager
# FIXME: consider a clean deinstall w/o deleting customized changes 
#  rm -rf $ADDON_DIR
rm -rf $ADDON_DIR/python
rm -rf $ADDON_DIR/pmatic
rm -rf $ADDON_DIR/examples
rm -rf $ADDON_DIR/manager_static
rm -rf $WWW_DIR

echo "create directories" >>$LOG_FILE
if [ ! -d $BIN_DIR ]; then
    mkdir -p $BIN_DIR
    chmod 755 $BIN_DIR
fi

if [ ! -d $ADDON_DIR ]; then
    mkdir -p $ADDON_DIR
    chmod 755 $ADDON_DIR
fi

if [ ! -d $RCD_DIR ]; then
    mkdir -p $RCD_DIR
    chmod 755 $RCD_DIR
fi

if [ ! -d $ADDON_DIR/scripts ]; then
    mkdir -p $ADDON_DIR/scripts
    chmod 755 $ADDON_DIR/scripts
fi

if [ ! -d $ADDON_DIR/etc ]; then
    mkdir -p $ADDON_DIR/etc
    chmod 755 $ADDON_DIR/etc
fi

if [ ! -d $WWW_DIR/etc ]; then
    mkdir -p $WWW_DIR
    chmod 755 $WWW_DIR
fi

# Make python executable shipped with pmatic available via PATH
echo "Make python executable" >>$LOG_FILE
ln -s ../etc/config/addons/pmatic/python/bin/$PYTHON_VER $BIN_DIR/$PYTHON_VER
cp python-wrapper $BIN_DIR/python3
chmod +x $BIN_DIR/python

cp pmatic-manager $BIN_DIR/
chmod +x $BIN_DIR/pmatic-manager

# copy all stuff and setup rc.d
echo "copy all stuff and setup rc.d" >>$LOG_FILE
cp -R python manager_static $ADDON_DIR/
cp -R examples $ADDON_DIR/scripts/
cp -R pmatic $ADDON_DIR/python/lib/$PYTHON_VER
ln -s python/lib/$PYTHON_VER/pmatic $ADDON_DIR/pmatic
cp pmatic.init $RCD_DIR/pmatic
chmod +x $RCD_DIR/pmatic

# copy www stuff
echo "copy www stuff" >>$LOG_FILE
cp -af www/* ${WWW_DIR}/
chmod 755 $WWWDIR
sync

if [ "$1" = "" ]; then
  echo "CCU1"
  lcdtool "Reboot...             "
  lcdtool -a 0x40 -t bin 00
  echo "x" > /dev/watchdog
  reboot
  while true ; do true ;  done
elif [ "$1" = "CCU2" ]; then
  echo "CCU2"
  # CCU2 always reboots after Addon/Firmware Update
elif [ "$1" = "CCU3" ]; then
  echo "CCU3"
  # CCU3 always reboots after Addon/Firmware Update
elif [ "$1" = "HM-RASPBERRYMATIC" ]; then
  echo "HM-RASPBERRYMATIC"
  # RASPBERRYMATIC always reboots after Addon/Firmware Update
fi
